const plantas = [
    {
        id: 1,
        nombre: 'Aloe Vera',
        imagen: 'img/images.jpeg',
        descripcion: 'Planta medicinal con propiedades curativas y fácil de cuidar.',
        precio: 10,
        stock: 12,
    },
    {
        id: 2,
        nombre: 'Cactus',
        imagen: 'img/images (1).jpeg',
        descripcion: 'Perfecto para decoración y requiere poco riego.',
        precio: 8,
        stock: 4,
    },
    {
        id: 3,
        nombre: 'Suculenta',
        imagen: 'img/images (2).jpeg',
        descripcion: 'Planta resistente y de fácil mantenimiento, ideal para interiores.',
        precio: 5,
        stock: 2,
    },
    {
        id: 4,
        nombre: 'Monstera Deliciosa',
        imagen: 'img/images (3).jpeg',
        descripcion: 'Planta tropical con hojas grandes y vistosas, ideal para interiores.',
        precio: 25,
        stock: 8,
    },
    {
        id: 5,
        nombre: 'Potos',
        imagen: 'img/images (4).jpeg',
        descripcion: 'Planta fácil de cuidar, perfecta para cualquier espacio.',
        precio: 12,
        stock: 22,
    },
    {
        id: 6,
        nombre: 'Helecho',
        imagen: 'img/images (2).jpeg',
        descripcion: 'Planta frondosa que necesita humedad y luz indirecta.',
        precio: 15,
        stock: 14,
    },
    {
        id: 7,
        nombre: 'Lavanda',
        imagen: 'img/planta-lavanda.jpg',
        descripcion: 'Planta aromática con flores vistosas, perfecta para jardines y balcones.',
        precio: 15,
        stock: 11,
    },
    {
        id: 8,
        nombre: 'Sansevieria',
        imagen: 'img/sanseviera-3l-macetero-aura-verde-oliva-20cm.jpg',
        descripcion: 'Conocida como lengua de suegra, es una planta resistente y purificadora de aire.',
        precio: 20,
        stock: 12,
    },
    {
        id: 9,
        nombre: 'Bonsái',
        imagen: 'img/images (6).jpeg',
        descripcion: 'Árbol miniatura, ideal para decorar interiores y exteriores.',
        precio: 50,
        stock: 6,
    },
    {
        id: 10,
        nombre: 'Ficus Lyrata',
        imagen: 'img/images (7).jpeg',
        descripcion: 'Planta de interior con grandes hojas verdes, perfecta para dar un toque tropical.',
        precio: 35,
        stock: 23,
    },
    {
        id: 11,
        nombre: 'Orquídea',
        imagen: 'img/images (8).jpeg',
        descripcion: 'Elegante planta con flores vistosas, ideal para decoración de interiores.',
        precio: 30,
        stock: 15,
    },
    {
        id: 12,
        nombre: 'Hierbabuena',
        imagen: 'img/images (9).jpeg',
        descripcion: 'Planta aromática fácil de cultivar, perfecta para infusiones y recetas.',
        precio: 7,
        stock: 18,
    }
];
